# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
project_name: entry_point
release:
  github:
    owner: vauxoo
    name: docker_entrypoint
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./main.go
    id: "entry_point"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goarch: 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .ProjectName }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
source:
  enabled: false
